required = [
"github.com/paulhindemith/dev-infra/hack",
"github.com/paulhindemith/dev-infra/hack/boilerplate",
"github.com/paulhindemith/dev-infra/third_party/cert-manager/cert-manager-0.12.0",
"github.com/paulhindemith/dev-infra/third_party/istio/istio-1.4.2",
"github.com/paulhindemith/dev-infra/third_party/knative/knative-0.11.1",
"knative.dev/test-infra/scripts",
]

[[constraint]]
  name = "github.com/labstack/echo"
  version = "v4.1.13"
  source = "https://github.com/labstack/echo.git"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.11"

[[override]]
  name = "knative.dev/serving"
  branch = "release-0.11"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "github.com/paulhindemith/dev-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
