required = [
"github.com/paulhindemith/dev-infra/hack",
"github.com/paulhindemith/dev-infra/hack/boilerplate",
"knative.dev/test-infra/scripts",
]

[[constraint]]
  name = "github.com/labstack/echo"
  branch = "master"
  source = "https://github.com/labstack/echo.git"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "github.com/paulhindemith/dev-infra"
  non-go = false

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
